// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxwc_kZw3YFpZVMUOOeCMHxladZV9u6YI',
    appId: '1:332365761450:web:abbafa4e02e55d7d8179d3',
    messagingSenderId: '332365761450',
    projectId: 'bistro-8e287',
    authDomain: 'bistro-8e287.firebaseapp.com',
    storageBucket: 'bistro-8e287.firebasestorage.app',
    measurementId: 'G-QSBS5F3S0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmmy3bY5WmkXn_bSOonQnPa_8UwepDyeo',
    appId: '1:332365761450:android:8e90a4a7765c305f8179d3',
    messagingSenderId: '332365761450',
    projectId: 'bistro-8e287',
    storageBucket: 'bistro-8e287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YPcxKeth2pipAD1WsNZ2O8dLXyLN60k',
    appId: '1:332365761450:ios:9ebaa573be4c55418179d3',
    messagingSenderId: '332365761450',
    projectId: 'bistro-8e287',
    storageBucket: 'bistro-8e287.firebasestorage.app',
    iosBundleId: 'com.example.bistro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YPcxKeth2pipAD1WsNZ2O8dLXyLN60k',
    appId: '1:332365761450:ios:9ebaa573be4c55418179d3',
    messagingSenderId: '332365761450',
    projectId: 'bistro-8e287',
    storageBucket: 'bistro-8e287.firebasestorage.app',
    iosBundleId: 'com.example.bistro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxwc_kZw3YFpZVMUOOeCMHxladZV9u6YI',
    appId: '1:332365761450:web:d93368f10160099c8179d3',
    messagingSenderId: '332365761450',
    projectId: 'bistro-8e287',
    authDomain: 'bistro-8e287.firebaseapp.com',
    storageBucket: 'bistro-8e287.firebasestorage.app',
    measurementId: 'G-CXCQDXJS9J',
  );
}
